###MAKE AN ORDER
POST http://localhost:3000/api/order/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0NTZkZjhmYy01M2NiLTQ3NTQtYTY1NS1mZmNjMDc1MmQzYjAiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzIwMTE3ODgzLCJleHAiOjE3MjAyMDQyODN9.UAffBmFJXjEWMl7FxEwjeYfPP7NFewkD10TzEwtAxEQ
Content-Type: application/json

{
    "userId":"456df8fc-53cb-4754-a655-ffcc0752d3b0"
}

###GET ORDERS BY ID
GET http://localhost:3000/api/order/ed9ce3aa-b912-4027-aa62-126b282a5116

###MARK ORDER AS COMPLETED
PUT http://localhost:3000/api/order/d507cfd6-734f-4e72-9894-44f46364c830
Authorization: Bearer 

