### REGISTER A USER
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "name": "clinton",
    "email": "clinton@gmail.com",
    "password": "clinton"
}

### LOGIN A USER
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "morine@gmail.com",
    "password": "morine"
}

### GET USER PROFILE
GET http://localhost:3000/api/user/22e69b45-3dc9-46bb-ae17-009d0f4c2a02
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNTQzZTg4Yi01OTA2LTQ2YmQtOGJjZi1kNWY5OTM4MzQzYTMiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM5Mjc0NTk5LCJleHAiOjE3MzkzNjA5OTl9.kLQbRmoPWNreQ7HLVkNAa2pRUtn-7dkg-IEVmeF--fI

### ACTIVATE USER ACCOUNT
POST http://localhost:3000/api/user/activate
Content-Type: application/json

{
    "email": "morine@gmail.com",
    "activationCode": "2566"
}

### RESET USER PASSWORD
POST http://localhost:3000/api/user/reset-password
Content-Type: application/json

{
    "email": "morine@gmail.com",
    "newPassword": "morine"
}

### UPDATE USER PROFILE
PUT http://localhost:3000/api/user/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNTQzZTg4Yi01OTA2LTQ2YmQtOGJjZi1kNWY5OTM4MzQzYTMiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM5Mjc0NTk5LCJleHAiOjE3MzkzNjA5OTl9.kLQbRmoPWNreQ7HLVkNAa2pRUtn-7dkg-IEVmeF--fI

{
    "name": "morine",
    "email": "morine@gmail.com",
    "password": "morine"
}
