### REGISTER A USER
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "name": "Clinton Omari",
    "email": "clintonarani@gmail.com",
    "password": "clinton1234"
}

### LOGIN A USER
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "clintonarani@gmail.com",
    "password": "clinton1234"
}

### GET USER PROFILE
GET http://localhost:3000/api/user/c2253f75-8be8-47fc-9ebe-00f7733c9950
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjMjI1M2Y3NS04YmU4LTQ3ZmMtOWViZS0wMGY3NzMzYzk5NTAiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MzkzNzAwOTQsImV4cCI6MTczOTQ1NjQ5NH0.sTyzOKtveemwQwqOpSWZjk2g8wJb8SH_pH3XlbVtp1A

### ACTIVATE USER ACCOUNT
POST http://localhost:3000/api/user/activate
Content-Type: application/json

{
    "email": "clintonarani@gmail.com",
    "activationCode": "3724"
}

### RESET USER PASSWORD
POST http://localhost:3000/api/user/reset-password
Content-Type: application/json

{
    "email": "clintonarani@gmail.com",
    "newPassword": "password123"
}

### UPDATE USER PROFILE
PUT http://localhost:3000/api/user/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjMjI1M2Y3NS04YmU4LTQ3ZmMtOWViZS0wMGY3NzMzYzk5NTAiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MzkzNzEzMjQsImV4cCI6MTczOTQ1NzcyNH0.Qqcd6I5KS3FnQAhPyXI2B-6C7YL6V0kQpirO-xyNaOk

{
    "name": "clinton omari",
    "email": "clintonarani@gmail.com",
    "password": "clinton1234"
}
