### ADD ITEM TO CART
POST http://localhost:3900/cart-items/add
Content-Type: application/json

{
    "user_id": "a568cd46-1854-47c6-82be-fca9b1818e12",
    "product_id": "4cc60cba-f53b-45bc-8ea9-3d5b65fd3fb5",
    "quantity": 4
}

### REMOVE ITEM FROM CART
DELETE http://localhost:3900/cart-items/remove/6cb43afa-5388-451c-a32b-119272bc7a00
Content-Type: application/json

### GET CART ITEMS FOR A USER
GET http://localhost:3900/cart-items/items/a568cd46-1854-47c6-82be-fca9b1818e12
Content-Type: application/json