### INITIATE PASSWORD RESET (Send reset code to email)
POST http://localhost:3900/users/forgot-password
Content-Type: application/json

{
"email": "clintonarani@gmail.com"
}

### VERIFY RESET CODE
POST http://localhost:3900/users/verify-reset-code
Content-Type: application/json

{
"email": "clintonarani@gmail.com",
"resetCode": "123456"
}

### RESET PASSWORD (After code verification)
POST http://localhost:3900/users/reset-password
Content-Type: application/json

{
"email": "clintonarani@gmail.com",
"resetCode": "123456",
"newPassword": "NewPassword@123"
}